# Generated by Django 6.0.3 on 2026-03-24 01:33

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0003_placedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='places.place')),
            ],
        ),
    ]
