# Generated by Django 6.0.3 on 2026-04-19 23:16

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeminiEmbeddingVector',
            fields=[
                ('embeddingvector_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recommendation.embeddingvector')),
                ('vector', pgvector.django.vector.VectorField(dimensions=768)),
            ],
            bases=('recommendation.embeddingvector',),
        ),
        migrations.CreateModel(
            name='OpenAIEmbeddingVector',
            fields=[
                ('embeddingvector_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recommendation.embeddingvector')),
                ('vector', pgvector.django.vector.VectorField(dimensions=1536)),
            ],
            bases=('recommendation.embeddingvector',),
        ),
        migrations.CreateModel(
            name='LlmInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(max_length=60)),
                ('prompt_version', models.CharField(max_length=60)),
                ('embedding_model', models.CharField(max_length=100)),
                ('language_model', models.CharField(max_length=100)),
                ('input_payload', models.JSONField()),
                ('raw_llm_response', models.TextField()),
                ('parsed_output', models.JSONField(null=True)),
                ('outcome', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='places.place')),
            ],
        ),
    ]
