# Generated by Django 6.0.3 on 2026-04-20 00:34

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiEmbeddingVectorLarge',
            fields=[
                ('embeddingvector_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recommendation.embeddingvector')),
                ('vector', pgvector.django.vector.VectorField(dimensions=3072)),
            ],
            bases=('recommendation.embeddingvector',),
        ),
    ]
