# Generated by Django 6.0.3 on 2026-04-18 13:42

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeembedding",
            name="vector",
            field=pgvector.django.vector.VectorField(dimensions=3072),
        ),
    ]
