"""
Django settings for ferv_project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# load_dotenv(Path(__file__).resolve().parent.parent.parent / '.env')
load_dotenv(override=False)  # Las variables del sistema operativo tienen prioridad

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uz=tirdi_#%&@z9j#f+md6d4w@$kj@8hf#0(*(*oe5aq_+pkz!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'pgvector.django',

    'graph',
    'places',
    'recommendation',
    'user',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ferv_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ferv_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'ferv_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '1234'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5433'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Custom user model
AUTH_USER_MODEL = 'user.FervUser'

# Redirects
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/graph/welcome/'
LOGOUT_REDIRECT_URL = '/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Recommendation system config

EMBEDDING_MODELS = {
    "gemini-embedding-001": {
        "model_key": "gemini-embedding-001",
        "name": "models/gemini-embedding-001",
        "dimensions": 768,
        "api_key_env_var": "GEMINI_API_KEY",
    },
    "gemini-embedding-001-large": {
        "model_key": "gemini-embedding-001-large",
        "name": "models/gemini-embedding-001",
        "dimensions": 3072,
        "api_key_env_var": "GEMINI_API_KEY",
    },
    "openai-text-embedding-3-small": {
        "model_key": "openai-text-embedding-3-small",
        "name": "text-embedding-3-small",
        "dimensions": 1536,
        "api_key_env_var": "OPENAI_API_KEY",
    }
}

LANGUAGE_MODELS = {
    "gemini-2.5-flash": {
        "name": "gemini-2.5-flash",
        "api_key_env_var": "GEMINI_API_KEY",
    },
    "gemini-2.5-pro": {
        "name": "gemini-2.5-pro",
        "api_key_env_var": "GEMINI_API_KEY",
    },
    "openai-gpt-4o-mini": {
        "name": "gpt-4o-mini",
        "api_key_env_var": "OPENAI_API_KEY",
    }
}

RECOMMENDATION_CONFIGS = {
    "default": {
        "embedding_model": EMBEDDING_MODELS["gemini-embedding-001-large"],
        "language_model": LANGUAGE_MODELS["gemini-2.5-flash"],
    },
}
