# Generated by Django 6.0.3 on 2026-03-23 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=500)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('price_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hours', models.JSONField(blank=True, default=list)),
                ('review_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='places.place')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('place', 'tag'), name='unique_place_tag')],
            },
        ),
    ]
