# Generated by Django 6.0.3 on 2026-03-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='editorial_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
