# Generated by Django 6.0.3 on 2026-03-23 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_editorial_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='places.place')),
            ],
        ),
    ]
