# Generated by Django 6.0.3 on 2026-04-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fervuser',
            name='soft_characteristics',
            field=models.TextField(blank=True, help_text='Características suaves o preferencias adicionales del usuario.'),
        ),
    ]
